version: '2'

volumes:
  pgdata:
    driver: local

services:
  django:
    build: ./docker/
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
      - 3000:3000
    volumes:
      - ./django:/web
    depends_on:
      - pgsql

  pgsql:
    image: postgres:9.4
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Wibble123!
